Using unit abbreviations instead of full name when viewing a recipe
nazgul26/PHPRecipebook pull request #50
Opened 2017-01-23 20:36 UTC by maxmikk

When viewing a recipe, the full unit name used to be displayed. This change will use the abbreviation instead.

2017-01-28 21:18 UTC, nazgul26 requested changes
Thanks for jumping in.  I know it is lot to get started with Git and all this.  Congrats on submitted the pull request.  Please see the review comments.

2017-01-28 21:18 UTC, nazgul26 commented on View/Recipes/view.ctp
> +                            $ingredientName = $related['Related']['IngredientMapping'][$i]['Ingredient']['name'];
Not quite a revert.  You have a trailing space added.  I know small, but please remove.

2017-01-28 21:18 UTC, nazgul26 commented on Controller/RecipesController.php
> +                            'fields' => array('name', 'abbreviation') //2017-01-23 - added 'abbreviation' to be able to view those in the recipe view.
Remove the comments.  We have source control for comments.  I know you mean well, but if every change was dated in code it quickly becomes unreadable overall.  Same goes for the other comments/dates.

2017-01-29 07:26 UTC, maxmikk commented
Comments removed.

2017-01-31 01:09 UTC, merged